#!/usr/bin/env node
var accountDirectory = "/home/mmartinez";
var providerPMTAConfig = "/etc/pmta/config.d/ool-yrly.conf";
var provider = new Array();
provider["optonline"] = accountDirectory + "/accounts-20140429-OOL.txt";
provider["roadrunner"] = accountDirectory + "/accounts-20140429-RR.txt";

if(process.argv.length == 3){
	var providerConfig = provider[process.argv[2]];
	if(providerConfig){
		console.log("Targetting: " + process.argv[2]);
		console.log("Loading provider config: " + providerConfig);
		var Process = require("child_process").exec;
		var FileSystem = require("fs");

		FileSystem.readFile(providerConfig, function(error, data){
			if(error){
				console.log(error);
			}
			else{
				FileSystem.writeFile(providerPMTAConfig, data, function(error, data){
					if(error){
						console.log(error);
					}

				});
			}

		});

		Process("sudo service pmta reload", function(error, output){
			if(error){
				console.log(error);
			}
			console.log(output);
		});


	}
	
	

}